import logger from "@/utils/logger";
import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        const apiKey = process.env.GEMINI_API_KEY;

        const body = await req.json();
        const { productQuery, category } = body;

        const ai = new GoogleGenAI({ apiKey });

        const geminiRes = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: `
                QUERY: ${productQuery}
                CATEGORY: ${category}
            `,
            config: {
                systemInstruction: `
                    You are an expert in generating SEO titles for product searchs.

                    Create a good SEO title for Amazon search for this product: "${productQuery}" in the category "${category}". 
                    The title should be optimized for search visibility and include relevant keywords. 
                    Give me only the SEO title, nothing else. Example: "red shirt 3xl men" should look somethink like 
                    “Men's 3XL Red Casual Shirt - Plus Size Cotton Button Down for Everyday & Party Wear”
                    `,
            },
        });

        const generatedContent = geminiRes.text;
        if (!generatedContent) throw new Error("No content generated by AI");

        let title = generatedContent.trim();
        logger.log("API Generated SEO title:", title);

        return NextResponse.json({ data: title }, { status: 200, statusText: "SEO title generated successfully" });
    } catch (err: any) {
        logger.error("Error in generate-seo-title route", err);

        return NextResponse.json(
            { success: false, error: err?.message || "Invalid request" },
            { status: 400, statusText: err?.message?.error?.message || "Invalid request" }
        );
    }
}
